certDir: /certs
clientCAFile: /tmp/gatekeeper/ca.crt
port: 8090
provider:
  timeout: 1
  tls:
    caBundle: ""
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
