apiVersion: v1
kind: Service
metadata:
  name: attest-provider
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    run: attest-provider
  sessionAffinity: None
